// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.HelloWorld2;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSubsystemLeftFrontController;
    public static SpeedController driveSubsystemLeftRearController;
    public static SpeedController driveSubsystemRightFrontController;
    public static SpeedController driveSubsystemRightRearController;
    public static RobotDrive driveSubsystemRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSubsystemLeftFrontController = new Talon(0);
        LiveWindow.addActuator("DriveSubsystem", "LeftFrontController", (Talon) driveSubsystemLeftFrontController);
        
        driveSubsystemLeftRearController = new Talon(1);
        LiveWindow.addActuator("DriveSubsystem", "LeftRearController", (Talon) driveSubsystemLeftRearController);
        
        driveSubsystemRightFrontController = new Talon(2);
        LiveWindow.addActuator("DriveSubsystem", "RightFrontController", (Talon) driveSubsystemRightFrontController);
        
        driveSubsystemRightRearController = new Talon(3);
        LiveWindow.addActuator("DriveSubsystem", "RightRearController", (Talon) driveSubsystemRightRearController);
        
        driveSubsystemRobotDrive = new RobotDrive(driveSubsystemLeftFrontController, driveSubsystemLeftRearController,
              driveSubsystemRightFrontController, driveSubsystemRightRearController);
        
        driveSubsystemRobotDrive.setSafetyEnabled(true);
        driveSubsystemRobotDrive.setExpiration(0.1);
        driveSubsystemRobotDrive.setSensitivity(0.5);
        driveSubsystemRobotDrive.setMaxOutput(1.0);

        driveSubsystemRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveSubsystemRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
